/**
 * Sinhala FM Fonts & Modern Typography System for Wedding Invitations.
 *
 * Provides:
 * 1. Curated font choices including FM Abhaya (Abhaya Libre), FM Gemunu (Gemunu Libre),
 *    Noto Serif Sinhala, and Noto Sans Sinhala.
 * 2. Official UCSC / LTRL algorithmic Unicode to FMAbhaya converter
 *    (for graphic design export, print cards, and Photoshop workflows).
 */

export type SinhalaFontKey = 'abhaya' | 'gemunu' | 'noto-serif' | 'noto-sans';

export interface SinhalaFontOption {
  key: SinhalaFontKey;
  name: string;
  nameSi: string;
  badge: string;
  description: string;
  descriptionSi: string;
  cssClass: string;
  cssFamily: string;
}

export const SINHALA_FONTS: SinhalaFontOption[] = [
  {
    key: 'abhaya',
    name: 'FM Abhaya (Abhaya Libre)',
    nameSi: 'සම්ප්‍රදායික අභය (FM Abhaya)',
    badge: 'Classic Serif • පුවත්පත් සම්ප්‍රදාය',
    description: 'The golden standard of Sri Lankan formal print & classic wedding cards. Created by master typographer Pushpananda Ekanayake.',
    descriptionSi: 'ශ්‍රී ලාංකේය සාම්ප්‍රදායික මංගල ආරාධනා සඳහා වඩාත් ප්‍රචලිත අභය අකුරු මෝස්තරය.',
    cssClass: 'font-sinhala-abhaya',
    cssFamily: '"Abhaya Libre", "Noto Serif Sinhala", serif',
  },
  {
    key: 'gemunu',
    name: 'FM Gemunu (Gemunu Libre)',
    nameSi: 'රාජකීය ගැමුණු (FM Gemunu)',
    badge: 'Royal Display • තේජාන්විත අකුරු',
    description: 'Majestic, square-edged royal Sri Lankan typeface. Bold and authoritative with high screen clarity.',
    descriptionSi: 'පෝරු මස්තකාරූඪ සහ තේජාන්විත රාජකීය උත්සව සඳහා උචිත ගැමුණු අකුරු මෝස්තරය.',
    cssClass: 'font-sinhala-gemunu',
    cssFamily: '"Gemunu Libre", "Abhaya Libre", sans-serif',
  },
  {
    key: 'noto-serif',
    name: 'Royal Serif (Noto Serif Sinhala)',
    nameSi: 'රාජකීය සෙරිෆ් (Royal Serif)',
    badge: 'Deluxe Curves • අලංකාර වක්‍ර',
    description: 'High-contrast, literary Sinhala serif with graceful calligraphic curves and ornate flourishes.',
    descriptionSi: 'ඉතා අලංකාර, වක්‍රාකාර කැලිග්‍රැෆික් මෝස්තරයක් සහිත සුඛෝපභෝගී අකුරු විලාසිතාව.',
    cssClass: 'font-sinhala-noto-serif',
    cssFamily: '"Noto Serif Sinhala", "Abhaya Libre", serif',
  },
  {
    key: 'noto-sans',
    name: 'Modern Clean (Noto Sans Sinhala)',
    nameSi: 'නවීන සරල (Modern Sans)',
    badge: 'Contemporary • සරල හා පිරිසිදු',
    description: 'Clean, unmodulated contemporary aesthetic. Perfect for modern minimalist and outdoor beach weddings.',
    descriptionSi: 'පැහැදිලි හා සරල නවීන විලාසිතාවේ අකුරු මෝස්තරය.',
    cssClass: 'font-sinhala-noto-sans',
    cssFamily: '"Noto Sans Sinhala", sans-serif',
  },
];

export function getSinhalaFontOption(key?: string): SinhalaFontOption {
  return SINHALA_FONTS.find((f) => f.key === key) || SINHALA_FONTS[0];
}

export function getSinhalaFontClass(key?: string): string {
  const opt = getSinhalaFontOption(key);
  return `font-sinhala ${opt.cssClass}`;
}

/**
 * Official UCSC / LTRL Unicode to FMAbhaya Transliteration Table.
 * Converts Unicode Sinhala into legacy FM-Abhaya / FM-Bindumathi visual ASCII encoding.
 * Essential for exporting couple names to Photoshop, Illustrator, and CorelDRAW.
 */
const UNICODE_TO_FM_RULES: Array<{ p: RegExp; r: string }> = [
  { p: /ද්‍රෝ/g, r: 'føda' },
  { p: /ඤූ/g, r: 'ü' },
  { p: /ඣි/g, r: '¯' },
  { p: /ර්‍ය/g, r: '©' },
  { p: /ද්‍රෞ/g, r: 'fø!' },
  { p: /ද්‍රෙ/g, r: 'fø' },
  { p: /ද්‍රේ/g, r: 'føa' },
  { p: /ද්‍රො/g, r: 'fød' },
  { p: /ද්‍ර/g, r: 'ø' },
  { p: /ත්‍රෛ/g, r: 'ff;%' },
  { p: /ශෛ/g, r: 'ffY' },
  { p: /චෛ/g, r: 'ffp' },
  { p: /ජෛ/g, r: 'ffc' },
  { p: /කෛ/g, r: 'ffl' },
  { p: /මෛ/g, r: 'ffu' },
  { p: /පෛ/g, r: 'ffm' },
  { p: /දෛ/g, r: 'ffo' },
  { p: /තෛ/g, r: 'ff;' },
  { p: /නෛ/g, r: 'ffk' },
  { p: /ධෛ/g, r: 'ffO' },
  { p: /වෛ/g, r: 'ffj' },
  { p: /ප්‍රෞ/g, r: 'fm%!' },
  { p: /ක්‍ෂ්‍යෝ/g, r: 'fÌHda' },
  { p: /ෂ්‍යෝ/g, r: 'fIHda' },
  { p: /ඡ්‍යෝ/g, r: 'fPHda' },
  { p: /ඪ්‍යෝ/g, r: 'fVHda' },
  { p: /ඝ්‍යෝ/g, r: 'f>Hda' },
  { p: /ඛ්‍යෝ/g, r: 'fLHda' },
  { p: /ළ්‍යෝ/g, r: 'f<Hda' },
  { p: /ඵ්‍යෝ/g, r: 'fMHda' },
  { p: /ඨ්‍යෝ/g, r: 'fGHda' },
  { p: /ශ්‍යෝ/g, r: 'fYHda' },
  { p: /බ්‍යෝ/g, r: 'fnHda' },
  { p: /ච්‍යෝ/g, r: 'fpHda' },
  { p: /ඩ්‍යෝ/g, r: 'fâHda' },
  { p: /ෆ්‍යෝ/g, r: 'f*Hda' },
  { p: /ග්‍යෝ/g, r: 'f.Hda' },
  { p: /ජ්‍යෝ/g, r: 'fcHda' },
  { p: /ක්‍යෝ/g, r: 'flHda' },
  { p: /ල්‍යෝ/g, r: 'f,Hda' },
  { p: /ම්‍යෝ/g, r: 'fuHda' },
  { p: /න්‍යෝ/g, r: 'fkHda' },
  { p: /ප්‍යෝ/g, r: 'fmHda' },
  { p: /ද්‍යෝ/g, r: 'foHda' },
  { p: /ස්‍යෝ/g, r: 'fiHda' },
  { p: /ට්‍යෝ/g, r: 'fgHda' },
  { p: /ව්‍යෝ/g, r: 'fjHda' },
  { p: /ත්‍යෝ/g, r: 'f;Hda' },
  { p: /භ්‍යෝ/g, r: 'fNHda' },
  { p: /ධ්‍යෝ/g, r: 'fOHda' },
  { p: /ථ්‍යෝ/g, r: 'f:Hda' },
  { p: /ය්‍යෝ/g, r: 'fhHda' },
  { p: /ක්‍ෂ්‍රෝ/g, r: 'fÌ%da' },
  { p: /ෂ්‍රෝ/g, r: 'fI%da' },
  { p: /ශ්‍රෝ/g, r: 'fY%da' },
  { p: /බ්‍රෝ/g, r: 'fn%da' },
  { p: /ක්‍රෝ/g, r: 'fl%da' },
  { p: /ප්‍රෝ/g, r: 'fm%da' },
  { p: /ස්‍රෝ/g, r: 'fi%da' },
  { p: /ට්‍රෝ/g, r: 'fg%da' },
  { p: /ත්‍රෝ/g, r: 'f;%da' },
  { p: /ධ්‍රෝ/g, r: 'fO%da' },
  { p: /බ්‍රේ/g, r: 'fí%' },
  { p: /ක්‍රේ/g, r: 'fla%' },
  { p: /ප්‍රේ/g, r: 'fma%' },
  { p: /ස්‍රේ/g, r: 'fia%' },
  { p: /ත්‍රේ/g, r: 'f;a%' },
  { p: /ශ්‍රේ/g, r: 'fY%a' },
  { p: /බ්‍රෙ/g, r: 'fn%' },
  { p: /ක්‍රෙ/g, r: 'fl%' },
  { p: /ප්‍රෙ/g, r: 'fm%' },
  { p: /ස්‍රෙ/g, r: 'fi%' },
  { p: /ත්‍රෙ/g, r: 'f;%' },
  { p: /්‍ය/g, r: 'H' },
  { p: /බ්‍රි/g, r: 'ì%' },
  { p: /්‍ර/g, r: '%' },
  { p: /බෞ/g, r: 'fn!' },
  { p: /ගෞ/g, r: 'f.!' },
  { p: /කෞ/g, r: 'fl!' },
  { p: /මෞ/g, r: 'fu!' },
  { p: /නෞ/g, r: 'fk!' },
  { p: /පෞ/g, r: 'fm!' },
  { p: /දෞ/g, r: 'fo!' },
  { p: /සෞ/g, r: 'fi!' },
  { p: /තෞ/g, r: 'f;!' },
  { p: /බෝ/g, r: 'fnda' },
  { p: /චෝ/g, r: 'fpda' },
  { p: /ඩෝ/g, r: 'fvda' },
  { p: /ගෝ/g, r: 'f.da' },
  { p: /හෝ/g, r: 'fyda' },
  { p: /ජෝ/g, r: 'fcda' },
  { p: /කෝ/g, r: 'flda' },
  { p: /ලෝ/g, r: 'f,da' },
  { p: /මෝ/g, r: 'fuda' },
  { p: /නෝ/g, r: 'fkda' },
  { p: /පෝ/g, r: 'fmda' },
  { p: /දෝ/g, r: 'foda' },
  { p: /රෝ/g, r: 'frda' },
  { p: /සෝ/g, r: 'fida' },
  { p: /ටෝ/g, r: 'fgda' },
  { p: /වෝ/g, r: 'fjda' },
  { p: /තෝ/g, r: 'f;da' },
  { p: /යෝ/g, r: 'fhda' },
  { p: /ධෝ/g, r: 'fOda' },
  { p: /බො/g, r: 'fnd' },
  { p: /ගො/g, r: 'f.d' },
  { p: /හො/g, r: 'fyd' },
  { p: /කො/g, r: 'fld' },
  { p: /ලො/g, r: 'f,d' },
  { p: /මො/g, r: 'fud' },
  { p: /නො/g, r: 'fkd' },
  { p: /පො/g, r: 'fmd' },
  { p: /දො/g, r: 'fod' },
  { p: /රො/g, r: 'frd' },
  { p: /සො/g, r: 'fid' },
  { p: /ටො/g, r: 'fgd' },
  { p: /වො/g, r: 'fjd' },
  { p: /තො/g, r: 'f;d' },
  { p: /යො/g, r: 'fhd' },
  { p: /බේ/g, r: 'fí' },
  { p: /ගේ/g, r: 'f.a' },
  { p: /හේ/g, r: 'fya' },
  { p: /පේ/g, r: 'fma' },
  { p: /කේ/g, r: 'fla' },
  { p: /ලේ/g, r: 'f,a' },
  { p: /මේ/g, r: 'fï' },
  { p: /නේ/g, r: 'fka' },
  { p: /දේ/g, r: 'foa' },
  { p: /රේ/g, r: 'f¾' },
  { p: /සේ/g, r: 'fia' },
  { p: /වේ/g, r: 'fõ' },
  { p: /තේ/g, r: 'f;a' },
  { p: /යේ/g, r: 'fha' },
  { p: /බෙ/g, r: 'fn' },
  { p: /ගෙ/g, r: 'f.' },
  { p: /හෙ/g, r: 'fy' },
  { p: /කෙ/g, r: 'fl' },
  { p: /ලෙ/g, r: 'f,' },
  { p: /මෙ/g, r: 'fu' },
  { p: /නෙ/g, r: 'fk' },
  { p: /පෙ/g, r: 'fm' },
  { p: /දෙ/g, r: 'fo' },
  { p: /රෙ/g, r: 'fr' },
  { p: /සෙ/g, r: 'fi' },
  { p: /ටෙ/g, r: 'fg' },
  { p: /වෙ/g, r: 'fj' },
  { p: /තෙ/g, r: 'f;' },
  { p: /යෙ/g, r: 'fh' },
  { p: /තු/g, r: ';=' },
  { p: /ශු/g, r: 'Y=' },
  { p: /ගු/g, r: '.=' },
  { p: /කු/g, r: 'l=' },
  { p: /රු/g, r: 're' },
  { p: /රූ/g, r: 'rE' },
  { p: /ආ/g, r: 'wd' },
  { p: /ඇ/g, r: 'we' },
  { p: /ඈ/g, r: 'wE' },
  { p: /ඌ/g, r: 'W!' },
  { p: /ඖ/g, r: 'T!' },
  { p: /ඒ/g, r: 'ta' },
  { p: /ඕ/g, r: '´' },
  { p: /ඳි/g, r: '¢' },
  { p: /ඳී/g, r: '£' },
  { p: /දූ/g, r: '¥' },
  { p: /දී/g, r: '§' },
  { p: /ලූ/g, r: 'Æ' },
  { p: /දි/g, r: 'È' },
  { p: /ච්/g, r: 'É' },
  { p: /ජ්/g, r: 'Ê' },
  { p: /රී/g, r: 'Í' },
  { p: /රි/g, r: 'ß' },
  { p: /බි/g, r: 'ì' },
  { p: /බ්/g, r: 'í' },
  { p: /බී/g, r: 'î' },
  { p: /ම්/g, r: 'ï' },
  { p: /මි/g, r: 'ñ' },
  { p: /මී/g, r: 'ó' },
  { p: /ව්/g, r: 'õ' },
  { p: /ඳු/g, r: '÷' },
  { p: /වී/g, r: 'ù' },
  { p: /වි/g, r: 'ú' },
  { p: /දු/g, r: 'ÿ' },
  { p: /ණී/g, r: 'Œ' },
  { p: /ණි/g, r: '‚' },
  { p: /ග/g, r: '.' },
  { p: /ක්‍ෂ/g, r: 'CI' },
  { p: /ෂ/g, r: 'I' },
  { p: /ං/g, r: 'x' },
  { p: /ඹ/g, r: 'U' },
  { p: /ඡ/g, r: 'P' },
  { p: /ඪ/g, r: 'V' },
  { p: /ඝ/g, r: '>' },
  { p: /ඊ/g, r: 'B' },
  { p: /ඛ/g, r: 'L' },
  { p: /ළ/g, r: '<' },
  { p: /ඟ/g, r: 'Õ' },
  { p: /ණ/g, r: 'K' },
  { p: /ඵ/g, r: 'M' },
  { p: /ඨ/g, r: 'G' },
  { p: /ෆ/g, r: '*' },
  { p: /ල/g, r: ',' },
  { p: /ථ/g, r: ':' },
  { p: /ත/g, r: ';' },
  { p: /භ/g, r: 'N' },
  { p: /ධ/g, r: 'O' },
  { p: /උ/g, r: 'W' },
  { p: /ශ/g, r: 'Y' },
  { p: /ඤ/g, r: '[' },
  { p: /ඉ/g, r: 'b' },
  { p: /ජ/g, r: 'c' },
  { p: /ට/g, r: 'g' },
  { p: /ය/g, r: 'h' },
  { p: /ස/g, r: 'i' },
  { p: /ව/g, r: 'j' },
  { p: /න/g, r: 'k' },
  { p: /ක/g, r: 'l' },
  { p: /ප/g, r: 'm' },
  { p: /බ/g, r: 'n' },
  { p: /ද/g, r: 'o' },
  { p: /ච/g, r: 'p' },
  { p: /ර/g, r: 'r' },
  { p: /එ/g, r: 't' },
  { p: /ම/g, r: 'u' },
  { p: /ඩ/g, r: 'v' },
  { p: /අ/g, r: 'w' },
  { p: /හ/g, r: 'y' },
  { p: /ඳ/g, r: '|' },
  { p: /ැ/g, r: 'e' },
  { p: /ෑ/g, r: 'E' },
  { p: /ෙ/g, r: 'f' },
  { p: /ු/g, r: 'q' },
  { p: /ි/g, r: 's' },
  { p: /ූ/g, r: 'Q' },
  { p: /ී/g, r: 'S' },
  { p: /ෘ/g, r: 'D' },
  { p: /ෲ/g, r: 'DD' },
  { p: /ෟ/g, r: '!' },
  { p: /ා/g, r: 'd' },
  { p: /්/g, r: 'a' },
];

/**
 * Converts modern Unicode Sinhala text into FM-Abhaya ASCII character string.
 * Used for exporting to desktop publishing software (Photoshop, InDesign, Illustrator).
 */
export function unicodeToFmAbhaya(text: string): string {
  if (!text) return '';
  return UNICODE_TO_FM_RULES.reduce((acc, rule) => acc.replace(rule.p, rule.r), text);
}
